// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Airplane
{
    public string Id { get; set; }

    public string Code { get; set; }

    public string Type { get; set; }

    public int AvailableSeat { get; set; }

    public string AirlinesId { get; set; }

    public virtual Airline Airlines { get; set; }

    public virtual ICollection<Flight> Flights { get; set; } = new List<Flight>();
}