// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class BookingInformation
{
    public string Id { get; set; }

    public DateTime CreatedDate { get; set; }

    public string FlightId { get; set; }

    public string UserId { get; set; }

    public string Status { get; set; }

    public virtual Flight Flight { get; set; }

    public virtual ICollection<PassengerOfBooking> PassengerOfBookings { get; set; } = new List<PassengerOfBooking>();

    public virtual ICollection<PaymentRecord> PaymentRecords { get; set; } = new List<PaymentRecord>();

    public virtual User User { get; set; }
}