// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Flight
{
    public string Id { get; set; }

    public string AirplaneId { get; set; }

    public DateTime DepartureTime { get; set; }

    public DateTime ArrivalTime { get; set; }

    public string RouteId { get; set; }

    public string Status { get; set; }

    public string Class { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public virtual Airplane Airplane { get; set; }

    public virtual ICollection<BookingInformation> BookingInformations { get; set; } = new List<BookingInformation>();

    public virtual Route Route { get; set; }
}