// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class PaymentRecord
{
    public string Id { get; set; }

    public string BookingId { get; set; }

    public string UserId { get; set; }

    public decimal Price { get; set; }

    public decimal? Discount { get; set; }

    public decimal FinalPrice { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? PayDate { get; set; }

    public string Status { get; set; }

    public virtual BookingInformation Booking { get; set; }

    public virtual User User { get; set; }
}