// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Rank
{
    public string Id { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public decimal? Discount { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}