// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Relative
{
    public string Id { get; set; }

    public string UserId { get; set; }

    public string PassengerId { get; set; }

    public virtual Passenger Passenger { get; set; }

    public virtual User User { get; set; }
}