// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Route
{
    public string Id { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public virtual ICollection<Flight> Flights { get; set; } = new List<Flight>();

    public virtual Airport FromNavigation { get; set; }

    public virtual Airport ToNavigation { get; set; }
}