// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class User
{
    public string Id { get; set; }

    public string Avatar { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Address { get; set; }

    public int Point { get; set; }

    public string RankId { get; set; }

    public string Role { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BookingInformation> BookingInformations { get; set; } = new List<BookingInformation>();

    public virtual ICollection<PaymentRecord> PaymentRecords { get; set; } = new List<PaymentRecord>();

    public virtual Rank Rank { get; set; }

    public virtual ICollection<Relative> Relatives { get; set; } = new List<Relative>();
}